name: Rust CI

on:
  push:
    branches:
      - rust-backend
  pull_request:
    branches:
      - rust-backend

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Install SQLx CLI
      run: cargo install sqlx-cli --no-default-features --features sqlite
    - name: Run SQLx Migrations
      run: sqlx migrate run --database-url sqlite:notification.db
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


